<a href="https://colab.research.google.com/github/mohrilshriyash/MyGitRepo/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Working with Python Numpy Library

In [1]:
import numpy as np

1)Creating Numpy array

To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [ ]:
a=np.arange(5)
print(a)
print(type(a))

[0 1 2 3 4]
<class 'numpy.ndarray'>


NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.



In [ ]:
print(np.__version__)

1.25.2


In [ ]:
arr=np.array([10,12,34])
print(arr)

[10 12 34]


Types of Numpy arrays and its dimensions

In [ ]:
# 0-D arrays
arr0=np.array(100)
print(arr0.ndim) #to find the dimension of an nd array

arr1=np.array([12,14])
print(arr1.ndim)

arr2=np.array([[45,56,23,45],
              [13,45,90,80]])
print(arr2.ndim)

arr3=np.array([[[3,5,4],[7,8,9],
              [4,7,8],[55,3,6]]])
print(arr3.ndim)

0
1
2
3


In [ ]:
## Creating heigher dim arrays
arr_high=np.array([1,2,3,4],ndmin=5) #creates a 5d array
print(arr_high)

[[[[[1 2 3 4]]]]]


# Creating special Numpy Arrays

# Zeros

In [ ]:
## Array filled with Zeros

#1d array
zero_1=np.zeros(4)
print(zero_1)

# 2D array
zero_2=np.zeros((3,4))
print("2D array",zero_2)

# 3D array
zero_3=np.zeros((2,2,3))
print(zero_3)

[0. 0. 0. 0.]
2D array [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


#Ones

In [ ]:
ones_1=np.ones(2)
print(ones_1)

print()
ones_2=np.ones((2,2))
print(ones_2)

print()
ones_3=np.ones(((2,2,2)))
print(ones_3)

[1. 1.]

[[1. 1.]
 [1. 1.]]

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


# Empty Array

In [ ]:
emp=np.empty(3)
print(emp)

[0. 0. 0.]


In [ ]:
#Range

In [ ]:
range_1=np.arange(4)
print(range_1)

[0 1 2 3]


# Diagonal elements 1

In [ ]:
dia_1d=np.eye(3)
print(dia_1d)
print()

dia_2d=np.eye(4,4)
print(dia_2d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Array with intervals

In [ ]:
lin= np.linspace(0,20,5)
print(lin)

[ 0.  5. 10. 15. 20.]


#CREATING NUMPY ARRAYS USING RANDOM NUMBERS
1. rand()
2. randn()
3. ranf()
4. randint()

In [ ]:
# rand() : to generate randon numbers between 0 and 1  only positive
arr1=np.random.rand(4)
print(arr1)

print()
arr2=np.random.rand(3,3)
print(arr2)

[0.7548644  0.77708044 0.78160651 0.82603553]

[[0.89162551 0.18509132 0.58830605]
 [0.16154358 0.61366526 0.24627078]
 [0.8937111  0.78604625 0.03656738]]


In [ ]:
# randn() : generate numbers between 0 and1 both positive and -ve
arr3=np.random.randn(4)
print(arr3)

[ 0.42371693  0.64363367 -1.07730076 -0.15127358]


In [ ]:
# randf() : to generate numbers between 0 and excluding 1
arr4= np.random.ranf(4)
print(arr4)

[0.35209453 0.73681205 0.27879925 0.97793273]


In [ ]:
# randint(): to generate numbers betweeen any 2 numbers
#randint(start,end,no of items)
arr5= np.random.randint(2,10,4)
print(arr5)

[9 4 2 2]


#Arithmatic Operations in Numpy

Addition

In [ ]:
a1=np.array([3,4,5])
a2=np.array([5,6,7])

print(a1+a2)


[ 8 10 12]


In [ ]:
print(np.add(a1,a2))

[ 8 10 12]


Subtraction

In [ ]:
a=np.array([9,8,4])
b=np.array([3,4,5])
print(a-b)

[ 6  4 -1]


In [ ]:
print(np.subtract(a,b))

[ 6  4 -1]


Multiplication

In [ ]:
am=np.array([4,5,6])
an=np.array([8,9,10])
print(am*an)
print(np.multiply(am,an))

[32 45 60]
[32 45 60]


Divide


In [ ]:
ad=np.array([10,12,14])
bd=np.array([2,4,4])
print(ad/bd)
print(np.divide(ad,bd))

[5.  3.  3.5]
[5.  3.  3.5]


Modulas

In [ ]:
c=np.array([7,8,9])
d=np.array([2,3,4])
print(c%d)
print(np.mod(c,d))

[1 2 1]
[1 2 1]


Power and reciprocal

In [ ]:
p=np.array([2,3,4,5])
q=np.array([2,2,3,3])
print(p**q)
print(np.power(p,q))

[  4   9  64 125]
[  4   9  64 125]


Operations on 2D arrays

In [ ]:
arr1=np.array([[4,3,2],[5,3,1]])
arr2=np.array([[6,7,8],[9,8,7]])

print("add",np.add(arr1,arr2))
print()
print("sub",np.subtract(arr1,arr2))
print()
print("multiply",np.multiply(arr1,arr2))
print()
print("divide",np.divide(arr1,arr2))
print()
print("exponat",np.power(arr1,arr2))


add [[10 10 10]
 [14 11  8]]

sub [[-2 -4 -6]
 [-4 -5 -6]]

multiply [[24 21 16]
 [45 24  7]]

divide [[0.66666667 0.42857143 0.25      ]
 [0.55555556 0.375      0.14285714]]

exponat [[   4096    2187     256]
 [1953125    6561       1]]


#Arithmatic Functions in Numpy

In [ ]:
arry=np.array([10,12,14,16,18])
print(np.min(arry))#to find min val of array
print(np.max(arry))#to find max val of array
print(np.argmin(arry))#to find index of min value in array
print(np.argmax(arry))#to find index of max value in array
print(np.sqrt(arry))#to find sq root of items
print(np.cumsum(arry)) # to find cummulative sum of items (prevterm+presentterm )
print()
arr2=([90,150,270])
print(np.cos(arr2))
print(np.sin(arr2))

10
18
0
4
[3.16227766 3.46410162 3.74165739 4.         4.24264069]
[10 22 36 52 70]

[-0.44807362  0.69925081  0.98438195]
[ 0.89399666 -0.71487643 -0.17604595]


#Shape and Reshaping in NumPy Arrays

In [ ]:
ary=np.array([[1,2],
              [1,2]])
print(np.ndim(ary))
print(np.shape(ary))
print()

ary2=np.array([[1,2,3,4],
              [1,2,3,4]])
print(np.ndim(ary2))
print(np.shape(ary2))

2
(2, 2)

2
(2, 4)


Changing dimension of an array

In [ ]:
ary3=np.array([4,5,6,7],ndmin=3)
print(np.ndim(ary3)) #[[[4,5,6,7]]]
print(np.shape(ary3))

3
(1, 1, 4)


Reshaping a numpy array

In [ ]:
ary4=np.array([3,4,5,6,7,8])
print(ary4.reshape(3,2)) #converting a (1X6) array to (3X2)
print(ary4.shape)
print(ary4.ndim)
#print(ary4.reshape(2,2)) #reshape(rows,column) note rows and col must be compatible with data in orignal array

[[3 4]
 [5 6]
 [7 8]]
(6,)
1


In [ ]:
#converting a multidim array to 1d arry
ar_mult=np.array([[[3,4,5],[5,6,7],[9,10,11],
                   [4,3,1],[4,9,5],[9,8,5],
                   [23,34,56],[95,59,90],[56,45,55]]])
print(ar_mult.shape())
print(ar_mult.ndim)

TypeError: 'tuple' object is not callable

Slicing/ Indexing In Numpy Arrays

In [ ]:
var1=np.array([1,2,3,4,5])
print(var1.ndim)
print(var1.shape)
print(var1[3])

var2=np.array([[3,4,5],
              [6,7,8]])
print(var2.ndim)
print(var2.shape)
print(var2[0][2])
print(var2[1][1])

print()

var3=np.array([[[5,6,7],[2,4,5]]])
print(var3.ndim)
print(var3.shape)
print(var3[0,0,1])

1
(5,)
4
2
(2, 3)
5
7

3
(1, 2, 3)
6


In [ ]:
# slicing
v1=np.array([9,8,7,6,5,3,1,2])
print(v1[1:])
print(v1[:3])
print(v1[::2])

print()

v2=np.array([[3,4,5,6],
             [9,8,7,0]])
print(v2[0,1:])
print(v2[1,2:])

[8 7 6 5 3 1 2]
[9 8 7]
[9 7 5 1]

[4 5 6]
[7 0]


# Broadcasting of Numpy array

In [ ]:
# prompt: iter

import numpy as np

# Create a 1-D array
a = np.array([1, 2, 3, 4, 5])
#shape(1,5)

# Create a 2-D array
b = np.array([[1, 2, 3], [4, 5, 6]])
#shape(2,3)

# Add the 1-D array to each row of the 2-D array
c = a + b

# Print the resulting array
print(c)
# it gives the broadcast error because the shape of 2 arrays added is not compatible to make them copatible we should use arrays
#of same shape


## Check the shapes of the arrays a and b using the shape attribute.
#If the shapes are different, try reshaping one of the arrays to have the same number of dimensions as the other.
#If the shapes are the same, check if the data types of the arrays are compatible for the operation you are trying to perform.
#If the data types are not compatible, try converting one of the arrays to a compatible data type.



ValueError: operands could not be broadcast together with shapes (5,) (2,3) 

In [ ]:
ar1=np.array([[2],[4]])
print(ar1.shape)

ar2=np.array([[5,3,2],[6,7,8]])
print(ar2.shape)

print(ar1+ar2)
print((ar1+ar2).shape)

(2, 1)
(2, 3)
[[ 7  5  4]
 [10 11 12]]
(2, 3)


# Numpy Iteration

In [5]:
#1D
a1=np.array([1,2,3,4])
print(a1)

print()

for i in a1:
  print(i)

#2d
a2=np.array([[4,3,2,1],[6,7,8,9]])
print(a2)
print()
#since it is a 2d aray we need to iterate 2times to get individual values of array

for j in a2:
  for k in j:
    print(k)


[1 2 3 4]

1
2
3
4
[[4 3 2 1]
 [6 7 8 9]]

4
3
2
1
6
7
8
9


In [7]:
#3D
a3=np.array([[[10,11,12],[13,14,15],[16,1,18]]])
print(a3.ndim)
print(a3)
print()

for p in a3:
  for q in p:
    for r in q:
      print(r)

3
[[[10 11 12]
  [13 14 15]
  [16  1 18]]]

10
11
12
13
14
15
16
1
18


Iterating numpy array without for loop

In [ ]:
#nditer()
a1=np.array([1,2,3,4])
print(a1)